### ISSUE TITLE
Generate document id before storing document

### ISSUE THREAD

**Issue by devbrandonlong** [mdowds/python-mock-firestore#1]
Hello! 

Thanks for making this library! Saved me a ton of time for my unit testing.

I am having an issue trying to use the library to generate document ids like such:

```
post_id = db.collection("posts").document().id
```

I do this using the live Firestore client so I was hoping it'd be possible with the mock library.

**Comment by mdowds** [comment]
Hey, thanks for using it! 

I created it when doing tests for one of my projects, so only got as far as implementing the functionality I needed for that. Feel free to submit a PR though.

**Comment by mdowds** [comment]
Done as part of #6 , thanks to @christippett
