### ISSUE TITLE
DocumentSnapshot.id missing

### ISSUE THREAD

**Issue by satwell** [mdowds/python-mock-firestore#12]
The Google Firestore client has an id property available on DocumentSnapshot.  id seems to be set regardless of whether the document exists or not.

`id = client.collection('test').document('zzz').get().id`

id should be `'zzz'` in this example, but with mock-firestore, this raises `AttributeError: 'DocumentSnapshot' object has no attribute 'id'`.

**Comment by mdowds** [comment]
This was added in #11 (thanks @briggleman ) and included in version 0.4.
