### ISSUE TITLE
Deleting documents

### ISSUE THREAD

**Issue by devbrandonlong** [mdowds/python-mock-firestore#2]
Hello again! 

I also noticed that the delete() function for `DocumentReference` wasn't added.

I added the following to `main.py` as a quick fix but would love to hear your thoughts:

```    
def delete(self):
    get_by_path(self._data, self._path).clear()
```
I also tried:
```    
def delete(self):
    self.set({})
```

They both seemed to have similar behavior and passed my unit tests

**Comment by mdowds** [comment]
Thanks for the suggestion!

I think it would be better to remove both the key and value from the dictionary using `del`, so then it's consistent with the document not being created in the first place.

I'm not sure how that could be made to work with the nested dictionaries though. Either way the library doesn't handle non-present documents in the same way as the real Firestore does though, so I'm open to a PR.
