### ISSUE TITLE
Collection get() returns generator instead of list

### ISSUE THREAD

**Issue by yrunts** [mdowds/python-mock-firestore#3]
At least in python3.7 collection get method returns generator.
Mock returns list instead.

Propose change in Query class:
```
def get(self) -> Generator:
        return (DocumentSnapshot(doc) for doc in self._data.values())
```

**Comment by mdowds** [comment]
Good suggestion, I've modified Query as you suggested but set the return type as `Iterator` to match the real Firestore implementation.
