### ISSUE TITLE
Add support for using a document snapshot as the query cursor

### ISSUE THREAD

**Issue by carl-chipperfield** [mdowds/python-mock-firestore#35]
Add support for using a document snapshot as the query cursor to be able to paginate documents in a collection.   

Example:
```
doc = fs.collection('foo').document('1').get()
fs.collection('foo').order_by('id').start_after(doc).limit(2).stream()
```

[Docs](https://cloud.google.com/firestore/docs/query-data/query-cursors#use_a_document_snapshot_to_define_the_query_cursor)

**Comment by mdowds** [comment]
Closed by #36
