### ISSUE TITLE
Different instances don't share data

### ISSUE THREAD

**Issue by dezmaeth** [mdowds/python-mock-firestore#4]
In the intended use of different instances to unit test Firestore behavior, this is not available using MockFirestore:

ex:
```
fire_db_a = MockFirestore()
fire_db_b = MockFirestore()

doc_ref_a = fire_db.collection('test').document('abc')
doc_ref_a.set({ 'test': 'value'})
doc_ref_b = fire_db.collection('test').document('abc')
doc_ref_a.get().to_dict()
// returns {'test': 'value'}
doc_ref_b.get().to_dict()
// returns {}
```
returns should be the same

**Comment by mdowds** [comment]
What's the intended use of this? I can see shared state between instances causing issues with keeping unit tests isolated from one another.

**Comment by christippett** [comment]
@dezmaeth, you can share the same `MockFirestore` instance by instantiating it once and then using it in difference places. In my tests I monkeypatch `firestore.Client`, so no matter where in my code I'm using Firestore, I know it'll be writing to my mocked Firestore instance.

For example (using `pytest`):

```python
import pytest

from mockfirestore import MockFirestore
from google.cloud import firestore


@pytest.fixture(autouse=True)
def db(monkeypatch):
    mock_firestore = MockFirestore()
    with monkeypatch.context() as m:
        m.setattr(firestore, "Client", lambda: mock_firestore)
        yield mock_firestore
        mock_firestore.reset()
```

**Comment by dezmaeth** [comment]
@christippett Thank you, did it and worked
