### ISSUE TITLE
Support Collection.add

### ISSUE THREAD

**Issue by notnami** [mdowds/python-mock-firestore#8]
The `Collection` object in the real Firestore client offers the method `add`. This is the method we use to create new documents. Is there a particular reason that method was omitted from `MockFirestore`, or did the author just not get to it?

If it's the latter, I can try implementing it.

**Comment by mdowds** [comment]
Hi @notnami, I've taken the approach of adding stuff in as I've needed it for my own projects, as I don't have the time to build out a feature-complete version.

If you'd like to open a PR for `Collection.add` I'd be happy to look at it.

**Comment by mdowds** [comment]
Support added (among other things!) in #10
